### ISSUE TITLE
Please remove this warning Virus

### ISSUE THREAD

**Issue by chris1111** [MuntashirAkon/DPCIManager#1]
Compilling and build on macOS Mojave  Xcode Version 10.1 (10B61)
Take look here lots people afraid to using this app cause of this scan
Lots of Antivirus scan the app as virus
https://www.virustotal.com/fr/file/23c03646fd3ec7cf8fb1a20019533f856ea078e6bf192a640c311c7d79de7c9f/analysis/1541777751/

![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu320.png)

**Comment by MuntashirAkon** [comment]
These antivirus programs are detecting [`DirectHW.kext`](https://github.com/MuntashirAkon/DPCIManager/tree/master/DirectHW.kext) as a virus. Perhaps, I should remove this feature as they are not necessary these days?

**Comment by chris1111** [comment]
> These antivirus programs are detecting [`DirectHW.kext`](https://github.com/MuntashirAkon/DPCIManager/tree/master/DirectHW.kext) as a virus. Perhaps, I should remove this feature as they are not necessary these days?

For my part it would be much better to delete it if it is no longer necessary
People do not like to give something like no virus, considering all the security issues
If you do not remove it how can I build the app without this
Thanks

**Comment by MuntashirAkon** [comment]
The best way to remove it would be removing it after building the app, ie. After building the app, simply delete the `DirectHW.kext` from `DPCIManager.app/Contents/Resources`.

You can also remove it before building the app by removing `DirectHW.kext` from **Target Membership**. In the project navigator section, you'll find it at _DCPIManager > DCPIManager > Supporting Files_

**Comment by MuntashirAkon** [comment]
Then the virus scanners may be checking the binary file as well. Let me see if I find any workaround. If not, I'll remove it altogether.

**Comment by MuntashirAkon** [comment]
Checkout the Commit [254d780](https://github.com/MuntashirAkon/DPCIManager/commit/254d780baf716004b4f12c325ce2231470be5a6b). I've removed all the utilities that are no longer necessary.

**Comment by chris1111** [comment]
Thank you very much its ok 
https://www.virustotal.com/fr/file/282e86b78178c7d014ebdfa83311755616bfbdd14c7efb3a572b8ecd10d16393/analysis/1541876975/

But I need to add pci.ids because * build failed missing pci.ids *

**Comment by MuntashirAkon** [comment]
Look at the _scheme_ section of Xcode, you'll find an scheme named `PCI IDs` which adds the latest `pci.ids` to the project.
