### ISSUE TITLE
use of bundle identifier 'net.sourceforge.DPCIManager'

### ISSUE THREAD

**Issue by core-code** [MuntashirAkon/DPCIManager#2]
hello,

since this seems to be an inofficial fork of 'DPCIManager' please make sure you are not using the same bundle identifier as the original project 'net.sourceforge.DPCIManager'.

thanks

**Comment by MuntashirAkon** [comment]
Well, I've tried contacting the dev, but s/he's no longer active. Maybe I'll change the identifier in the next release.

**Comment by chris1111** [comment]
> Well, I've tried contacting the dev, but s/he's no longer active. Maybe I'll change the identifier in the next release.

Good  and maybe release 1.8 😀
Great job man!

**Comment by MuntashirAkon** [comment]
Implemented at [586a69d](https://github.com/MuntashirAkon/DPCIManager/commit/586a69d17322afa45cb83877fa3679a8ac09efed).

**Comment by core-code** [comment]
thanks!
