### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by webfalter** [MuntashirAkon/DPCIManager#3]
./dspci
Using PCI.IDs 2018.11.12
Caught: NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
 ./dspci --version
dspci version 1.8

**Comment by MuntashirAkon** [comment]
Did you compile it yourself, or are you using the released binary?

**Comment by webfalter** [comment]
Released Binary and as well as when I create this myself with xcode

**Comment by MuntashirAkon** [comment]
Ok, I'll try to fix the problem as soon as I'm free.

**Comment by MuntashirAkon** [comment]
Can you provide me with the output of
```
./dspci DTListPCIID
```
?

**Comment by webfalter** [comment]
./dspci DTListPCIID
Caught: NSInvalidArgumentException: * -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

**Comment by chris1111** [comment]
No issue here on macOS Mojave build Xcode Version 10.1 (10B61)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu329.png)

**Comment by webfalter** [comment]
@chris1111 
yours Using PCI.IDs 2018.11.**09**
Using PCI.IDs 2018.11.**12**
Does that have anything to do with the update of pci.ids?

**Comment by chris1111** [comment]
I try tonight when back to home

**Comment by MuntashirAkon** [comment]
@webfalter, since I cannot reproduce this issue on my machine, it's a bit hard for me to debug. I've made some changes to the repo as part of solving this issue. Please download/pull the latest repo and try again. This time only run `./dspci DTListPCIID` command and send me the output.

**Comment by webfalter** [comment]
```
./dspci DTListPCIID 
8086:190c
8086:191e
8086:1903
8086:9d2f
8086:9d60
8086:9d61
8086:9d3a
8086:9d03
8086:9d10
8086:9d18
8086:9d46
8086:9d21
8086:9d70
8086:9d23
144d:a804
8086:24f3
 ./dspci
Using PCI.IDs 2018.11.13
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers [8086:190c] (rev 08) (subsys 1d72:1501)
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 515 [8086:191e] (rev 07) (subsys 1d72:1501)
00:04.0 Signal processing controller [1180]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem [8086:1903] (rev 08) (subsys 1d72:1501)
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21) (subsys 8086:7270)
00:15.0 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 [8086:9d60] (rev 21) (subsys 1d72:1501)
00:15.1 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 [8086:9d61] (rev 21) (subsys 1d72:1501)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI #1 [8086:9d3a] (rev 21) (subsys 1d72:1501)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21) (subsys 1d72:1501)
00:1c.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 [8086:9d10] (rev f1)
00:1d.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 [8086:9d18] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation (null) [8086:9d46] (rev 21) (subsys 1d72:1501)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21) (subsys 1d72:1501)
00:1f.3 Audio device [0403]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d70] (rev 21) (subsys 1d72:1501)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21) (subsys 1d72:1501)
01:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961 [144d:a804] (subsys 144d:a801)
02:00.0 Network controller [0280]: Intel Corporation Wireless 8260 [8086:24f3] (rev 3a) (subsys 8086:9010)
./dspci --json
Caught: NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

```

**Comment by MuntashirAkon** [comment]
Please check out the latest commit. Specially with `--json` option.

**Comment by chris1111** [comment]
No issue here
Last login: Thu Nov 15 21:27:26 on ttys000
iMac-de-chris:~ chris$ ./dspci DTListPCIID 
8086:0100
8086:0101
8086:1c3a
8086:1502
8086:1c2d
8086:1c20
8086:1c10
8086:1c14
8086:1c18
8086:1c26
8086:244e
8086:1c4c
8086:1c02
8086:1c22
10de:128b
10de:0e0f
1b73:1100
1b4b:9230
12d8:e111
168c:002a
iMac-de-chris:~ chris$ ./dspci
Using PCI.IDs 2018.11.13
00:00.0 Host bridge [0600]: Intel Corporation 2nd Generation Core Processor Family DRAM Controller [8086:0100] (rev 09) (subsys 1028:04ad)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:0101] (rev 09)
00:16.0 Communication controller [0780]: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 [8086:1c3a] (rev 04) (subsys 1028:04ad)
00:19.0 Ethernet controller [0200]: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) [8086:1502] (rev 04) (subsys 1028:047e)
00:1a.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 [8086:1c2d] (rev 04) (subsys 1028:04ad)
00:1b.0 Audio device [0403]: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller [8086:1c20] (rev 04) (subsys 1028:04ad)
00:1c.0 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [8086:1c10] (rev b4)
00:1c.2 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 3 [8086:1c14] (rev b4)
00:1c.4 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [8086:1c18] (rev b4)
00:1d.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 [8086:1c26] (rev 04) (subsys 1028:04ad)
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev a4)
00:1f.0 ISA bridge [0601]: Intel Corporation Q65 Express Chipset LPC Controller [8086:1c4c] (rev 04) (subsys 1028:04ad)
00:1f.2 SATA controller [0106]: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller [8086:1c02] (rev 04) (subsys 1028:04ad)
00:1f.3 SMBus [0c05]: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller [8086:1c22] (rev 04) (subsys 1028:04ad)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK208B [GeForce GT 710] [10de:128b] (rev a1) (subsys 1458:0010)
01:00.1 Audio device [0403]: NVIDIA Corporation GK208 HDMI/DP Audio Controller [10de:0e0f] (rev a1) (subsys 1458:36f7)
03:00.0 USB controller [0c03]: Fresco Logic FL1100 USB 3.0 Host Controller [1b73:1100] (rev 10) (subsys 1b73:1100)
04:00.0 SATA controller [0106]: Marvell Technology Group Ltd. 88SE9230 PCIe SATA 6Gb/s Controller [1b4b:9230] (rev 11) (subsys 1b4b:9230)
05:02.0 PCI bridge [0604]: Pericom Semiconductor PI7C9X111SL PCIe-to-PCI Reversible Bridge [12d8:e111] (rev 02)
06:00.0 Network controller [0280]: Qualcomm Atheros AR928X Wireless Network Adapter (PCI-Express) [168c:002a] (rev 01) (subsys 11ad:6632)
iMac-de-chris:~ chris$ ./dspci --json
[
  {
    "Info" : {
      "Name" : "2nd Generation Core Processor Family DRAM Controller",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "0100"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "09",
    "BDF" : "00:00.0",
    "Class" : {
      "ID" : "0600",
      "ClassName" : "Bridge",
      "SubclassName" : "Host bridge"
    }
  },
  {
    "Info" : {
      "Name" : "Xeon E3-1200\/2nd Generation Core Processor Family PCI Express Root Port",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "0101"
    },
    "SubsysID" : {
      "VendorID" : "000f",
      "DeviceID" : "0000"
    },
    "Rev" : "09",
    "BDF" : "00:01.0",
    "Class" : {
      "ID" : "0604",
      "ClassName" : "Bridge",
      "SubclassName" : "PCI bridge"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family MEI Controller #1",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c3a"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:16.0",
    "Class" : {
      "ID" : "0780",
      "ClassName" : "Communication controller",
      "SubclassName" : "Communication controller"
    }
  },
  {
    "Info" : {
      "Name" : "82579LM Gigabit Network Connection (Lewisville)",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1502"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "047e"
    },
    "Rev" : "04",
    "BDF" : "00:19.0",
    "Class" : {
      "ID" : "0200",
      "ClassName" : "Network controller",
      "SubclassName" : "Ethernet controller"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family USB Enhanced Host Controller #2",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c2d"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:1a.0",
    "Class" : {
      "ID" : "0c03",
      "ClassName" : "Serial bus controller",
      "SubclassName" : "USB controller"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family High Definition Audio Controller",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c20"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:1b.0",
    "Class" : {
      "ID" : "0403",
      "ClassName" : "Multimedia controller",
      "SubclassName" : "Audio device"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family PCI Express Root Port 1",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c10"
    },
    "SubsysID" : {
      "VendorID" : "0000",
      "DeviceID" : "0000"
    },
    "Rev" : "b4",
    "BDF" : "00:1c.0",
    "Class" : {
      "ID" : "0604",
      "ClassName" : "Bridge",
      "SubclassName" : "PCI bridge"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family PCI Express Root Port 3",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c14"
    },
    "SubsysID" : {
      "VendorID" : "0000",
      "DeviceID" : "0000"
    },
    "Rev" : "b4",
    "BDF" : "00:1c.2",
    "Class" : {
      "ID" : "0604",
      "ClassName" : "Bridge",
      "SubclassName" : "PCI bridge"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family PCI Express Root Port 5",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c18"
    },
    "SubsysID" : {
      "VendorID" : "0000",
      "DeviceID" : "0000"
    },
    "Rev" : "b4",
    "BDF" : "00:1c.4",
    "Class" : {
      "ID" : "0604",
      "ClassName" : "Bridge",
      "SubclassName" : "PCI bridge"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family USB Enhanced Host Controller #1",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c26"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:1d.0",
    "Class" : {
      "ID" : "0c03",
      "ClassName" : "Serial bus controller",
      "SubclassName" : "USB controller"
    }
  },
  {
    "Info" : {
      "Name" : "82801 PCI Bridge",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "244e"
    },
    "SubsysID" : {
      "VendorID" : "0000",
      "DeviceID" : "0000"
    },
    "Rev" : "a4",
    "BDF" : "00:1e.0",
    "Class" : {
      "ID" : "0604",
      "ClassName" : "Bridge",
      "SubclassName" : "PCI bridge"
    }
  },
  {
    "Info" : {
      "Name" : "Q65 Express Chipset LPC Controller",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c4c"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:1f.0",
    "Class" : {
      "ID" : "0601",
      "ClassName" : "Bridge",
      "SubclassName" : "ISA bridge"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c02"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:1f.2",
    "Class" : {
      "ID" : "0106",
      "ClassName" : "Mass storage controller",
      "SubclassName" : "SATA controller"
    }
  },
  {
    "Info" : {
      "Name" : "6 Series\/C200 Series Chipset Family SMBus Controller",
      "Vendor" : "Intel Corporation"
    },
    "ID" : {
      "VendorID" : "8086",
      "DeviceID" : "1c22"
    },
    "SubsysID" : {
      "VendorID" : "1028",
      "DeviceID" : "04ad"
    },
    "Rev" : "04",
    "BDF" : "00:1f.3",
    "Class" : {
      "ID" : "0c05",
      "ClassName" : "Serial bus controller",
      "SubclassName" : "SMBus"
    }
  },
  {
    "Info" : {
      "Name" : "GK208B [GeForce GT 710]",
      "Vendor" : "NVIDIA Corporation"
    },
    "ID" : {
      "VendorID" : "10de",
      "DeviceID" : "128b"
    },
    "SubsysID" : {
      "VendorID" : "1458",
      "DeviceID" : "0010"
    },
    "Rev" : "a1",
    "BDF" : "01:00.0",
    "Class" : {
      "ID" : "0300",
      "ClassName" : "Display controller",
      "SubclassName" : "VGA compatible controller"
    }
  },
  {
    "Info" : {
      "Name" : "GK208 HDMI\/DP Audio Controller",
      "Vendor" : "NVIDIA Corporation"
    },
    "ID" : {
      "VendorID" : "10de",
      "DeviceID" : "0e0f"
    },
    "SubsysID" : {
      "VendorID" : "1458",
      "DeviceID" : "36f7"
    },
    "Rev" : "a1",
    "BDF" : "01:00.1",
    "Class" : {
      "ID" : "0403",
      "ClassName" : "Multimedia controller",
      "SubclassName" : "Audio device"
    }
  },
  {
    "Info" : {
      "Name" : "FL1100 USB 3.0 Host Controller",
      "Vendor" : "Fresco Logic"
    },
    "ID" : {
      "VendorID" : "1b73",
      "DeviceID" : "1100"
    },
    "SubsysID" : {
      "VendorID" : "1b73",
      "DeviceID" : "1100"
    },
    "Rev" : "10",
    "BDF" : "03:00.0",
    "Class" : {
      "ID" : "0c03",
      "ClassName" : "Serial bus controller",
      "SubclassName" : "USB controller"
    }
  },
  {
    "Info" : {
      "Name" : "88SE9230 PCIe SATA 6Gb\/s Controller",
      "Vendor" : "Marvell Technology Group Ltd."
    },
    "ID" : {
      "VendorID" : "1b4b",
      "DeviceID" : "9230"
    },
    "SubsysID" : {
      "VendorID" : "1b4b",
      "DeviceID" : "9230"
    },
    "Rev" : "11",
    "BDF" : "04:00.0",
    "Class" : {
      "ID" : "0106",
      "ClassName" : "Mass storage controller",
      "SubclassName" : "SATA controller"
    }
  },
  {
    "Info" : {
      "Name" : "PI7C9X111SL PCIe-to-PCI Reversible Bridge",
      "Vendor" : "Pericom Semiconductor"
    },
    "ID" : {
      "VendorID" : "12d8",
      "DeviceID" : "e111"
    },
    "SubsysID" : {
      "VendorID" : "0000",
      "DeviceID" : "0000"
    },
    "Rev" : "02",
    "BDF" : "05:02.0",
    "Class" : {
      "ID" : "0604",
      "ClassName" : "Bridge",
      "SubclassName" : "PCI bridge"
    }
  },
  {
    "Info" : {
      "Name" : "AR928X Wireless Network Adapter (PCI-Express)",
      "Vendor" : "Qualcomm Atheros"
    },
    "ID" : {
      "VendorID" : "168c",
      "DeviceID" : "002a"
    },
    "SubsysID" : {
      "VendorID" : "11ad",
      "DeviceID" : "6632"
    },
    "Rev" : "01",
    "BDF" : "06:00.0",
    "Class" : {
      "ID" : "0280",
      "ClassName" : "Network controller",
      "SubclassName" : "Network controller"
    }
  }
]
iMac-de-chris:~ chris$

**Comment by webfalter** [comment]
@MuntashirAkon 
Also works with the last commit https://github.com/MuntashirAkon/DPCIManager/commit/1ace5fa577942d3b84a4d32fe5be62c321361f48 --json option. Thank you
why it was too @chris1111 before, no idea
